name: Gource Action bump
on:
  push:
    branches:
      - main

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: 'Gource Action'
        uses: nbprojekt/gource-action@master
        with:
          args: 'TEMPLATE=none'
          git_url: 'https://github.com/kodadot/nft-gallery'
          gource_title: 'KodaDot NFT marketplace'
          logo_url: 'https://github.com/kodadot/kodadot-presskit/blob/main/v3/KODA_v3.png?raw=true'
          avatars_auto_fetch: 'true'
          gource_resolution: '720p'
          gource_fps: 60
          gource_font_size: 40
          gource_start_date: '2022-09-01'
          gource_dir_depth: 6
          gource_filename_time: 6
          gource_seconds_per_day: 0.1


      - name: 'Upload gource video'
        uses: actions/upload-artifact@v2
        with:
          name: Gource
          path: ./gource/gource.mp4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: action
          title: "[skip ci] update gource video"
          commit-message: "[skip ci] update gource video"
