name: Gource Action bump
on:
  push:
    branches:
      - main

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: 'Gource Action'
        uses: nbprojekt/gource-action@v1
        with:
          git_url: 'https://github.com/kodadot/nft-gallery'
          gource_title: 'KodaDot NFT marketplace'
          gource_resolution: '720p'
          gource_fps: 60
          gource_font_size: 40
          gource_start_date: '2022-10-01'
          gource_stop_date: '2019-12-01'

      - name: 'Upload gource video'
        uses: actions/upload-artifact@v2
        with:
          name: Gource
          path: ./gource/gource.mp4
